#============================================================================
# Project     : SRCNN_84
# File        : clean_sim.tcl
# Purpose     : Remove Vivado/xsim simulation byproducts.
#
# Usage:
#   vivado -nolog -nojournal -notrace -mode batch \
#     -source ./06_SRCNN_84/scripts/clean_sim.tcl
#
# Useful options:
#   -tclargs --dry-run  Print files that would be removed.
#   -tclargs --help     Print this help text.
#
# Notes:
#   - This script only removes simulation byproducts generated by the batch
#     flow or by direct xvlog/xelab/xsim runs from the repository root.
#   - It does not remove RTL, TB, init/ref data, or Vivado project files.
#============================================================================

#----------------------------------------------------------------------------
# Argument parsing
#----------------------------------------------------------------------------

set dry_run 0

foreach arg $argv {
    switch -- $arg {
        "--dry-run" {
            set dry_run 1
        }
        "--help" {
            puts "SRCNN_84 simulation cleanup"
            puts ""
            puts "Usage:"
            puts "  vivado -nolog -nojournal -notrace -mode batch -source ./06_SRCNN_84/scripts/clean_sim.tcl"
            puts ""
            puts "Options:"
            puts "  --dry-run  Print files that would be removed."
            puts "  --help     Print this message."
            exit 0
        }
        default {
            puts "ERROR: Unknown option: $arg"
            puts "Run with --help for usage."
            exit 1
        }
    }
}

#----------------------------------------------------------------------------
# Directory layout
#----------------------------------------------------------------------------

set script_dir [file dirname [file normalize [info script]]]
set srcnn_dir  [file normalize [file join $script_dir ".."]]
set repo_dir   [file normalize [file join $srcnn_dir ".."]]

#----------------------------------------------------------------------------
# Cleanup manifest
#----------------------------------------------------------------------------

set targets [list \
    [file join $repo_dir "xsim.dir"] \
    [file join $repo_dir "xvlog.log"] \
    [file join $repo_dir "xvlog.pb"] \
    [file join $repo_dir "xelab.log"] \
    [file join $repo_dir "xelab.pb"] \
    [file join $repo_dir "xsim.log"] \
    [file join $repo_dir "xsim.jou"] \
    [file join $srcnn_dir "sim_work"] \
]

foreach pattern [list \
    [file join $repo_dir "xsim_*.backup.log"] \
    [file join $repo_dir "xsim_*.backup.jou"] \
    [file join $srcnn_dir "sim_work_*"] \
] {
    foreach item [glob -nocomplain $pattern] {
        lappend targets $item
    }
}

#----------------------------------------------------------------------------
# Cleanup
#----------------------------------------------------------------------------

set remove_count 0
set warning_count 0

foreach item $targets {
    if {[file exists $item]} {
        if {$dry_run} {
            incr remove_count
            puts "Would remove $item"
        } else {
            puts "Removing $item"
            if {[catch {file delete -force $item} result]} {
                incr warning_count
                puts "  WARNING: Could not remove $item"
                puts "           $result"
            } else {
                incr remove_count
            }
        }
    }
}

if {$dry_run} {
    puts "Dry run complete. Matched $remove_count item(s)."
} else {
    puts "Simulation byproduct cleanup complete. Removed $remove_count item(s), warnings $warning_count."
}

exit 0
