# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/vio_0/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_0_ooc.xdc

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/vio_0/vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/vio_0/vio_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/ila_0/ila_0_ooc.xdc

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/vio_0/vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/rlaqj/Project/DSD/Lab/Lab01/Vivado/Vivado.gen/sources_1/bd/design_1/ip/design_1_top_0_0/src/top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
